targets:
    $default:
        builders:
            realm_generator|realm_object_builder:
                enabled: true
                generate_for:
                    - test/*.dart          
builders:
    #realm_object_builder:
        # this generates .realm.dart files. Requires a LibraryBuilder in builder.dart
        # import: "package:realm_generator/builder.dart"
        # builder_factories: ["generateRealmObjects"]
        # build_extensions: {".dart": [".realm.dart"]}
        # auto_apply: dependents
        # build_to: source
        # applies_builders: ["combining_builder"]

    realm_object_builder:
        import: "package:realm_generator/builder.dart"
        builder_factories: ["generateRealmObjects"]
        build_extensions: {".dart": [".g.dart"]}
        auto_apply: dependents
        build_to: cache
        applies_builders: ["source_gen|combining_builder"]