name: realm_generator
description: Generates Realm Objects from Realm schema defintions
version: 1.0.0

homepage: https://github.com/realm

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.38.5 <0.40.0"
  build: ^1.3.0
  build_runner: ^1.10.0
  build_resolvers: ^1.3.9
  source_gen: ^0.9.5