name: realm_generator
description: Generates RealmObject classes from Realm schema definitions. This package is part of the official MongoDB Realm SDK
version: 0.1.0-preview

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart 
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_runner: ^1.10.0
  build_resolvers: ^2.0.0
  source_gen: ^0.9.5