name: realm
description: The official Realm SDK for Flutter. 
  Realm is a mobile database - an alternative to SQLite and key-value stores.
version: 0.1.0-preview

homepage: https://www.realm.io
repository: https://github.com/realm/realm-dart
issue_tracker: https://github.com/realm/realm-dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  #realm_generator: ^0.1.0-preview
  realm_generator: 
    path: ../../generator
  
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.realm.realm_flutter
        pluginClass: RealmFlutterPlugin
      ios:
        pluginClass: RealmFlutterPlugin