name: realm_generator_example
description: Example app using realm generator
version: 0.1.0-preview

publish_to: none

homepage: https://realm.io

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_runner: ^1.10.0
  build_resolvers: ^2.0.0
  source_gen: ^0.9.5
  
  realm_generator:
    path: ../